dwg: move dwg->measurement to HEADER.MEASUREMENT
as header var. It is read from DXF as HEADER.
This fixes indxf for it most elegantly.
But we need to store it as BS, not RL, otherwise
in_dxf will complain:
ERROR: skipping HEADER: 9 $MEASUREMENT, wrong type code 70 <=> field RL