injson: fix Dwg_VALUEPARAM subclass
with a proper subclass name we can now almost import
ASSOCACTION's.

Missing: resolve of inlined Dwg_EvalVariant
ERROR: Unknown subclass field VALUEPARAM_vars.code
ERROR: Unknown subclass field VALUEPARAM_vars.u