guard get_first_owned_object first_entity
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f782e1db8b5 bp 0x7fffb
a38ff70 sp 0x7fffba38ff50 T0)
The signal is caused by a READ memory access.
Hint: address points to the zero page.
 #0 0x7f782e1db8b4 in get_first_owned_object /home/rurban/Software/libredwg/src/dwg.c:748:34
 #1 0x5048fb in output_BLOCK_HEADER /home/rurban/Software/libredwg/programs/dwg2SVG.c:211:9
 #2 0x50453d in output_SVG /home/rurban/Software/libredwg/programs/dwg2SVG.c:252:3
 #3 0x50453d in main /home/rurban/Software/libredwg/programs/dwg2SVG.c:361